/* Difference between Java & Other Languages:
    Other Languages such as C, C++ : Code --> Compiler --> Machine Code
    Java: Code --> Compiler --> Byte Code --> JVM --> Machine Code
This Byte code is universal. JVM is platform specific thus its Machine Code as well.
 */

/*
An Approach to programming that breaks programming problems into objects that interact with each other.
*/

//package Introduction;

public class Introduction {
    public static void main(String[] args){
        System.out.println("My First Java Program");
    }
}